# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{semantic_menu}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daniel Haran"]
  s.date = %q{2011-01-22}
  s.description = %q{A plugin to make rails menus easier to write}
  s.email = %q{}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README",
    "README.rdoc",
    "TODO"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "MIT-LICENSE",
    "README",
    "README.rdoc",
    "Rakefile",
    "TODO",
    "VERSION",
    "init.rb",
    "install.rb",
    "lib/semantic_menu.rb",
    "lib/semantic_menu/menu_helper.rb",
    "lib/semantic_menu/menu_item.rb",
    "lib/tasks/semantic_menu_tasks.rake",
    "public/semantic-menu.html",
    "public/stylesheets/semantic-menu.css",
    "semantic_menu.gemspec",
    "test/helper.rb",
    "test/test_semantic_menu.rb",
    "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/michaek/semantic_menu}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.2}
  s.summary = %q{A plugin to make rails menus easier to write}
  s.test_files = [
    "test/helper.rb",
    "test/test_semantic_menu.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

